services:
  aiden_app:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aiden.rule=Host(`aiden.dev.localhost`)"
      - "traefik.http.services.aiden.loadbalancer.server.port=8000"
      - "traefik.http.routers.aiden-media.rule=Host(`aiden.dev.localhost`) && PathPrefix(`/media`)"
      - "traefik.http.routers.aiden-media.middlewares=aiden-media-stripprefix"
      - "traefik.http.middlewares.aiden-media-stripprefix.stripprefix.prefixes=/media"
      - "traefik.http.routers.aiden-media.priority=10"
    networks:
      - aiden_network
    volumes:
      - ./aiden_app:/app/aiden_app
      - ./aiden_project:/app/aiden_project
      - ./manage.py:/app/manage.py
      - ./media:/app/media
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}

  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - aiden_network

  traefik:
    image: "traefik:v2.6"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    networks:
      - aiden_network
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  pgweb:
    image: sosedoff/pgweb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgweb.rule=Host(`pgweb.dev.localhost`)"
      - "traefik.http.services.pgweb.loadbalancer.server.port=8081"
    environment:
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}?sslmode=disable
      - DATABASE_READ_ONLY=true
    networks:
      - aiden_network
volumes:
  postgres_data:

networks:
  aiden_network:
    driver: bridge
