# Generated by Django 5.0.6 on 2024-05-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiden_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(upload_to="profile/"),
        ),
    ]
