# Generated by Django 5.0.6 on 2024-05-17 18:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiden_app", "0003_alter_userprofile_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileinfo",
            name="embeddings_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
