# Generated by Django 5.0.7 on 2024-07-11 15:04

import aiden_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiden_app", "0004_profileinfo_embeddings_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileinfo",
            name="cv_title",
            field=models.CharField(
                help_text="The professional title or headline for the CV",
                max_length=255,
                validators=[aiden_app.models.remove_special_characters],
            ),
        ),
        migrations.AlterField(
            model_name="profileinfo",
            name="photo_url",
            field=models.CharField(help_text="The name of the profile picture"),
        ),
    ]
