# Generated by Django 5.0.7 on 2024-08-19 14:30

import aiden_app.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiden_app", "0007_alter_education_user_alter_experience_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profileinfo",
            name="photo_url",
        ),
        migrations.AlterField(
            model_name="profileinfo",
            name="social_links",
            field=models.ManyToManyField(
                help_text="A list of social media linked with the individual", related_name="profiles", to="aiden_app.sociallink"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.URLField(blank=True, help_text="The URL of the project repository or website", null=True),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="url",
            field=models.URLField(blank=True, help_text="The URL of the individual's profile on the social media platform", null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(storage=aiden_app.storage.UUIDS3Boto3Storage(object_folder="photos"), upload_to=""),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(storage=aiden_app.storage.UUIDS3Boto3Storage(object_folder="documents"), upload_to="")),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="aiden_app.profileinfo")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
