# Generated by Django 5.0.7 on 2024-07-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiden_app", "0007_alter_education_user_alter_experience_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociallink",
            name="url",
            field=models.URLField(blank=True, help_text="The URL of the individual's profile on the social media platform", null=True),
        ),
    ]
