# Generated by Django 5.0.7 on 2024-08-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiden_app", "0009_remove_profileinfo_photo_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.URLField(blank=True, help_text="The URL of the project repository or website", null=True),
        ),
    ]
