# Generated by Django 5.0.7 on 2024-08-21 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aiden_app", "0009_conversation_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="user_profile",
        ),
    ]
