# Generated by Django 5.0.7 on 2024-07-30 20:57

import aiden_app.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiden_app", "0009_alter_userprofile_photo_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(storage=aiden_app.storage.UUIDS3Boto3Storage(), upload_to="documents/"),
        ),
    ]
