# Generated by Django 5.0.7 on 2024-07-30 21:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aiden_app", "0010_alter_userprofile_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profileinfo",
            name="photo_url",
        ),
    ]
